version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run test && npm run report-coverage
      - run: NODE_ENV=production STATS=true npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: ./dist
  docker-hub:
    docker:
      - image: circleci/node:8.4
    steps:
      - run: curl --request POST "$DOCKER_HUB_BUILD_TRIGGER_URL" || true
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - docker-hub:
          filters:
            branches:
              only:
                - master
          requires:
            - build
