version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run test && npm run report-coverage
      - run: NODE_ENV=production npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
          paths:
            - node_modules
